# Generated by Django 5.1.15 on 2026-09-24 20:14

import django.db.models.deletion
import django.utils.timezone
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default=portal.models.generate_application_id, editable=False, max_length=30, unique=True, verbose_name='Unique Application ID')),
                ('target_degree', models.CharField(choices=[('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree'), ('PhD', 'Doctoral Degree (PhD)'), ('Language', 'Chinese Language Program')], default='Bachelor', max_length=50)),
                ('preferred_university_name', models.CharField(blank=True, help_text='If university not in system list', max_length=200)),
                ('preferred_program_name', models.CharField(blank=True, help_text='e.g. MBBS, Computer Science & AI, International Trade', max_length=200)),
                ('target_intake', models.CharField(choices=[('Autumn 2026', 'Autumn Intake 2026 (September)'), ('Spring 2026', 'Spring Intake 2026 (March)'), ('Autumn 2027', 'Autumn Intake 2027 (September)')], default='Autumn 2026', max_length=50)),
                ('scholarship_preference', models.CharField(choices=[('CSC Type A', 'Chinese Government Scholarship (CSC Type A - Embassy)'), ('CSC Type B', 'Chinese Government Scholarship (CSC Type B - University High-Level)'), ('Belt and Road', 'Belt & Road / Silk Road Scholarship'), ('Provincial', 'Provincial Government Full / Partial Scholarship'), ('University President', 'University Presidential Scholarship'), ('Self Funded', 'Self-Funded (Tuition Discount)')], default='CSC Type B', max_length=50)),
                ('highest_qualification', models.CharField(help_text='e.g. Higher Secondary Certificate (HSC) / Bachelor of Science', max_length=150)),
                ('institute_name', models.CharField(help_text='Name of your college/university', max_length=200)),
                ('graduation_year', models.PositiveIntegerField(help_text='Year of completion, e.g. 2024')),
                ('cgpa_or_percentage', models.CharField(help_text='e.g. 3.80 / 4.00 or 85%', max_length=50)),
                ('english_proficiency', models.CharField(default='English Medium of Instruction (MOI)', help_text='e.g. IELTS 6.5, Duolingo 110, or English Medium Certificate', max_length=150)),
                ('status', models.CharField(choices=[('Submitted', '1. Submitted'), ('Document Checking', '2. Document Checking'), ('Applied', '3. Applied to University'), ('Under Review', '4. Under Review'), ('Admission', '5. Admission / JW202 Issued'), ('Visa', '6. Visa In Progress'), ('Completed', '7. Completed / Ready for Departure')], default='Submitted', max_length=50)),
                ('status_note', models.TextField(blank=True, default='Your application dossier has been received and queued for document verification by our counselor team.', verbose_name='Public Status Note (Visible to Student)')),
                ('has_missing_documents', models.BooleanField(default=False, verbose_name='Missing / Re-upload Required Alert')),
                ('missing_documents_note', models.TextField(blank=True, verbose_name='Specific Document Re-upload Instructions')),
                ('internal_counselor_notes', models.TextField(blank=True, verbose_name='Internal Counselor Notes (Private)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='universities.program')),
                ('preferred_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='universities.university')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='portal.studentapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport Bio Page'), ('photo', 'Passport-size White Background Photo'), ('certificate', 'Highest Degree Certificate / Graduation Certificate'), ('transcript', 'Official Academic Transcript / Marksheet'), ('cv', 'Curriculum Vitae (CV / Resume)'), ('study_plan', 'Study Plan / Statement of Purpose (SOP)'), ('rec_letter_1', 'Academic Recommendation Letter 1 (Professor)'), ('rec_letter_2', 'Academic Recommendation Letter 2 (Associate Professor)'), ('physical_exam', 'Foreigner Physical Examination Form (Medical Report)'), ('police_clearance', 'Non-Criminal Record Certificate (Police Clearance)'), ('english_cert', 'English Proficiency Certificate / MOI'), ('other', 'Other Supplementary Documents / Awards / Portfolio')], max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='student_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified & Approved'), ('action_required', 'Action Required / Re-upload Requested')], default='pending', max_length=30)),
                ('counselor_feedback', models.TextField(blank=True, help_text='Feedback if document needs to be replaced or re-scanned')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.studentapplication')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='WhatsApp / Phone Number')),
                ('nationality', models.CharField(default='Bangladesh', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=50, verbose_name='Passport Number')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='Passport Expiry Date')),
                ('current_address', models.TextField(blank=True, verbose_name='Present Address')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Person & Phone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='student_avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
