services:
  - type: web
    name: bright-edu-consultancy
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn bright_edu.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bright-edu-db
          property: connectionString
      - key: SERVE_MEDIA_FILES
        value: "True"

databases:
  - name: bright-edu-db
    databaseName: bright_edu_db
    user: bright_user
    plan: free
