# Generated by Django 5.1.15 on 2026-09-24 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone / WhatsApp Number')),
                ('desired_degree', models.CharField(blank=True, choices=[('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree'), ('PhD', 'PhD / Doctoral'), ('Language', 'Chinese Language Program'), ('Other', 'Other Programs')], max_length=50, verbose_name='Desired Degree')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Inquiry Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Marked as Read')),
                ('replied', models.BooleanField(default=False, verbose_name='Replied')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submission Date')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('china', 'Study in China & CSC'), ('application', 'Application & Documents'), ('visa', 'Visa & Travel Guidance'), ('scholarships', 'Scholarship Types & Eligibility'), ('general', 'General Consultancy Services')], default='china', max_length=50)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='Student Name')),
                ('home_country', models.CharField(default='Bangladesh', max_length=100, verbose_name='Home Country')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Student Photo')),
                ('university_admitted', models.CharField(max_length=200, verbose_name='University Admitted')),
                ('program_name', models.CharField(max_length=200, verbose_name='Program / Major')),
                ('degree_level', models.CharField(choices=[('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree'), ('PhD', 'PhD Degree'), ('Language', 'Language & Cultural Studies')], default='Bachelor', max_length=50)),
                ('scholarship_received', models.CharField(default='Chinese Government Scholarship (CSC) Full Fund', max_length=200, verbose_name='Scholarship Received')),
                ('quote', models.TextField(verbose_name='Student Review / Testimonial')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Rating (1-5)')),
                ('intake_year', models.CharField(default='2025/2026', max_length=20, verbose_name='Intake Year')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Show on Home Page')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Testimonial',
                'verbose_name_plural': 'Student Testimonials',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
