# Generated by Django 5.1.15 on 2026-09-24 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scholarship_type', models.CharField(choices=[('csc_type_a', 'Chinese Government Scholarship (CSC Type A - Bilateral)'), ('csc_type_b', 'Chinese Government Scholarship (CSC Type B - University High-Level)'), ('belt_road', 'Belt and Road / Silk Road Scholarship'), ('provincial', 'Provincial Government Scholarship (Zhejiang, Jiangsu, etc.)'), ('municipal', 'Municipal Mayor Scholarship (Shanghai, Beijing, etc.)'), ('university', 'University Presidential Full/Partial Scholarship'), ('enterprise', 'Corporate / Enterprise Sponsored Scholarship')], max_length=50)),
                ('coverage', models.CharField(help_text='e.g. 100% Tuition Waiver + Free Campus Accommodation + Monthly Stipend', max_length=250)),
                ('monthly_stipend', models.CharField(blank=True, help_text='e.g. 2,500 RMB (Bachelor), 3,000 RMB (Master), 3,500 RMB (PhD)', max_length=100)),
                ('eligibility', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('badge_color', models.CharField(default='bg-emerald-100 text-emerald-800 border-emerald-300', help_text='CSS badge classes', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='University Name')),
                ('chinese_name', models.CharField(blank=True, max_length=200, verbose_name='Chinese Name (Hanzi)')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(default='China', max_length=100)),
                ('ranking_national', models.PositiveIntegerField(blank=True, null=True, verbose_name='National Rank')),
                ('ranking_world', models.PositiveIntegerField(blank=True, null=True, verbose_name='QS/THE World Rank')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='universities/covers/')),
                ('cover_image_url', models.URLField(blank=True, help_text='Fallback external image URL if no file uploaded')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('campus_highlights', models.TextField(blank=True, help_text='List key campus facilities, labs, dorms')),
                ('has_csc_scholarship', models.BooleanField(default=True, verbose_name='CSC Scholarship Eligible')),
                ('has_provincial_scholarship', models.BooleanField(default=True, verbose_name='Provincial Scholarship Eligible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Feature on Home Page')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['ranking_national', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Program Name')),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('degree_level', models.CharField(choices=[('Bachelor', 'Bachelor Degree (Undergraduate)'), ('Master', 'Master Degree (Postgraduate)'), ('PhD', 'Doctoral Degree (PhD)'), ('Language', 'Non-Degree / Chinese Language Program')], default='Bachelor', max_length=50)),
                ('discipline', models.CharField(choices=[('Medicine', 'Medicine & MBBS (English Taught)'), ('Computer Science', 'Computer Science, AI & Software Engineering'), ('Engineering', 'Civil, Mechanical & Electrical Engineering'), ('Business', 'International Business, Trade & Finance'), ('Science', 'Natural Sciences & Biotechnology'), ('Chinese Language', 'Chinese Language & Cultural Studies'), ('Arts & Design', 'Arts, Architecture & Media'), ('Other', 'Other Academic Fields')], default='Engineering', max_length=50)),
                ('language_of_instruction', models.CharField(choices=[('English', 'English Taught'), ('Chinese', 'Chinese Taught (HSK required)'), ('Bilingual', 'Bilingual (English & Chinese)')], default='English', max_length=50)),
                ('duration_years', models.DecimalField(decimal_places=1, default=4.0, help_text='e.g. 4.0 years for Bachelor, 2.5 for Master', max_digits=3)),
                ('annual_tuition_cny', models.PositiveIntegerField(help_text='Annual tuition in RMB', verbose_name='Tuition Fee (CNY/Year)')),
                ('intake', models.CharField(choices=[('September', 'Autumn Intake (September)'), ('March', 'Spring Intake (March)'), ('Both', 'Both Spring & Autumn Intakes')], default='September', max_length=50)),
                ('application_deadline', models.CharField(default='June 30 / Rolling', help_text='e.g. May 30, 2026', max_length=100)),
                ('requirements', models.TextField(blank=True, help_text='Minimum GPA, age limit, language proficiency (IELTS/Duolingo or English MOI)')),
                ('curriculum_overview', models.TextField(blank=True, help_text='Core course modules and career pathways')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mark as Popular Program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scholarships', models.ManyToManyField(blank=True, related_name='programs', to='universities.scholarship')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'ordering': ['degree_level', 'title'],
                'unique_together': {('university', 'slug')},
            },
        ),
    ]
